### ISSUE TITLE
icecube2 fails on area project

### ISSUE THREAD

**Issue by AnttiLukats** [SpinalHDL/riscvSoftcoreContest#1]
ERROR - synthesis: ../../../netlist/up5kareaevn.v(1461): cannot open file Up5kAreaEvn.v_toplevel_soc_system_cpu_RegFilePlugin_regFile.bin. VERI-1012

**Comment by Dolu1990** [comment]
Ahh thanks, yes that's missing.
I just submited a fix. The netlist in that fix is the one with emulation (which will not pass the tests, as the emulation software isn't done)

So, the state of the Up5kAreaEvn stuff is : 
- 2 stage, fully interlocked (ported from VexRiscv which is 5 stages pipelined CPU)
- 0.39 Dmips/Mhz
- Without emulation, it pass all the requirements for 1583 LC (whole design), FMax is > 12  Mhz (not stressed)
- With the emulation of the useless CSR, the hardware is done, for 1387 LC, but software is WIP

I'm not realy expecting to have the smallest implementation, as there is some wasted ressource by the fact that it is based on a 5 stages pipelined CPU. But the goal is more to expand the application range of VexRiscv and to show some funny stuff of the VexRiscv framework (parametrization)

Just a trick, i got the best area synthesis with Icecube2 LSE

**Comment by AnttiLukats** [comment]
you will not pass with emulation at all. the test rewrite the mtvec and disable the emulation code. so that pass you must not use trap emulation. I know FAQ says otherwise, but it would void the test cases...

**Comment by AnttiLukats** [comment]
thanks for the trick! I was about to try out..

**Comment by Dolu1990** [comment]
> you will not pass with emulation at all. the test rewrite the mtvec and disable the emulation code. so that pass you must not use trap emulation. I know FAQ says otherwise, but it would void the test cases...

So the trick here (tell me if it's wrong), is to emulate the mtvec itself. Basicaly, each time there is an interruption/exception, the CPU jump to the emulation code without looking at the mtvec. By this why it should be fine.

My plane for emulation is to emulate : 
- mtvec, mscratch, mepc, mtval
Those 4 32 bits register are realy using much space/muxes.

Then from what i have seen, in "real world" application (let's say Zephyr), the only down side of this emulation is that it require a bit of flash + a little overhead when a interrupt/ecall happen. But all the things like mstatus/mie/mip/mcause aren't emulated

**Comment by Dolu1990** [comment]
Ahh sorry, my bad, will not emulate mepc.

**Comment by AnttiLukats** [comment]
if you emulate mtvec, then you just fake and cheat everything.. all compliance gone. my 2 cents,

mtvec should be done and implement as defined in the SPEC if you implement your own VISION of mtvec you violate the ISA Spec.

**Comment by Dolu1990** [comment]
I see the point, it is realy not clear what "Software emulation of less used CPU instructions" mean.
In another hand if we see emulating mtvec as a violation of the spec, why emulating mscratch would not be 
 a violation of the spec ? More generaly, all kinds of emulation mean violation of the spec ?

**Comment by AnttiLukats** [comment]
trap emulation okay does not mean csr register emulation ok :) so you can trap on some instruction, but on NOT on read-write access to some CSR register, there is hint that register emulation is okay, but not reg emulation!
You can take the left path to emulate all CSR instructions, and while emulating CSR instructions emulate also all CSR registers, but you will not know if emulating CSR instructions is okay ;)
And some tests rewrite the mtvec to test handler.

**Comment by Dolu1990** [comment]
So, i made some experiments, emulating mtvec + mscratch + mtval seem technicaly ok, but require the following changes/addition    to remain     compliant / not have side effects : 
- Emulation trap should not override mstatus / mepc registers, nearly free
- When a emulation trap happen, the PC value of the failded instruction should be stored into a readable CSR, which is area costly :(
- the register file need a shadow mechanism, which is free on FPGA.

The impact on practical performances is about 10 instruction per interrupt/ecall, which is realy nothing
mstatus/mepc/mip/mie CSR stay native, so, the practical impact of that emulation is close to none.

So the requirements for this emulation seem to reduce the gain of the emulation by half in my case XD

**Comment by AnttiLukats** [comment]
This is still bordercase, as you define new suprrmachine operating mode.
But this is thr only way to use trsp and pass tests. Id say trap emulation
is not ok, as it does not allow care implementing true macine mode to pass
tests. And right mscratch csn slso not be emulated.

Am Di., 13. Nov. 2018, 14:48 hat Dolu1990 <notifications@github.com>
geschrieben:

**Comment by Dolu1990** [comment]
Release date is soooooooon. Mouahahaha
