### ISSUE TITLE
How to use DSP-accelerated multiplication

### ISSUE THREAD

**Issue by xobs** [SpinalHDL/riscvSoftcoreContest#3]
The `README.md` states that this supports "multiplication using FPGA DSP blocks", however the given examples appear to generate MulPlugin and MulDivIterativePlugins.

Should these be using special plugins, or is their DSP-acceleration inferred some other way?

**Comment by Dolu1990** [comment]
MulPlugin  is implemented that way : 
https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/plugin/MulPlugin.scala#L74

Which infer 4 partial multiplication to execute a 32 bits multiplication.

The two synthesis tools used for the context were able to pick it up as DSP blocks. Probably not in the most optimal manner, but at least a portable one.

I don't know if yosys is happy with it.

There is no explicit DSP block implementation for  MUL instruction done  in VexRiscv yet.

**Comment by xobs** [comment]
The issue is that yosys doesn't yet properly infer the MUL16 blocks.  There's an open issue on this.  Once that happens it'll naturally support DSP-accelerated multiplication.
